### ISSUE TITLE
Small request, pin the postinstall task to a hash instead of branch name

### ISSUE THREAD

**Issue by airtonix** [Enteee/tls-tofu#1]
I'm looking at using your git mirror container. 

One major concern is that none of the dependencies described are pinned to a unique version so i can't be sure that each time i run the image in a CI environment that i'll be running the same  logic each time.

I'll start at the top: 

- https://github.com/Enteee/git-sync-mirror/blob/master/Dockerfile#L1
  - needs to point at a more specific tag (ideally a hash) than just `latest`
 
- https://github.com/Enteee/tls-tofu/blob/master/Dockerfile.alpine#L7
  - needs to point at a commit hash instead of a branch name

- https://github.com/Enteee/kamikaze/blob/master/install.sh#L6
  - this whole file probably needs to be processed when you make a kamikaze release so that it includes the release version there instead of just `latest` 
  - so needs to change to something like `"https://api.github.com/repos/${REPO}/releases/${VERSION:-'latest'}" \`
  - and up the top of the file have something like `VERSION=${1:"<<RELEASE_VERSION>>''}`
  - locally if you're using it you can prefix any shortcuts you have to run `VERSION=latest ./install.sh`
  - when you run your github release, include something that replaces `<<RELEASE_VERSION>>'` with the actuall version you released.

**Comment by airtonix** [comment]
appreciate the effort you've put into creating these series of repos that make the `git-sync-mirror` docker container possible :+1: 

With the above considerations, though I think you can also make it a serious contendor for github action/ bitbucket pipeline use

**Comment by Enteee** [comment]
Thank you for submitting this feature request. I understand the value of dependency pinning and I do support this. Currently the `tls-tofu` and the `git-sync-mirror` Dockerfile always give you the latest and greatest. I understand that this might cause troubles when building them as part of your CICD pipeline.

While I like your investigation, i do also think that pinning dependencies inside Dockerfiles is a step too much and is rarely every done because it creates too much maintenance overhead. That's why we build container images in the first place right ? :) 

But I will work on producing multiple versioned and labeled images in Dockerhub which should then also solve your use case. In your CICD pipeline you can then just pin to any of those versions.

As a workaround for now I can suggest installing a local artifactory, building and pushing the images to there manually once and then have all CICD runners pull the images from there. That way you always get  the same image during each run.

For actual dependency pinning that works (`apk`, `apt` and its friends are not really built for that), we would need to switch the whole container build to `nix`. Even though I do like this thought (huge `nix` fan here :)) I don't think i can find the time to actually do this now.

**Comment by Enteee** [comment]
I created a workflow and pushed the first versioned tag `v0.0.1` to docker hub. See [here](https://hub.docker.com/layers/enteee/tls-tofu/v0.0.1/images/sha256-6f79cc7f7623c5fb51a4cda88278c930e888e7d3e4164628ef4526cf4407e01e?context=repo). You can now pin to that image. Does this solve your issue?

**Comment by airtonix** [comment]
The core issue i think is that while you bake whatever version kamikaze might be into the image at the time it's created, there's no transparency as to what version that is exactly later on.

so when doing this like dealing with bugs and doing security review of images in use, we can't easily see what version it is. 

additionally, all my suggetions are tiny changes that can be fully automated right here in github with actions.

**Comment by airtonix** [comment]
anyway, I ended up going with something else. a simple git mirror command in our bitbucket pipelines to migrate over to github.

```
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'mirror repo'
        script:
          - |
            set -euf -o pipefail; 
            # clone it as a mirror
            git clone --mirror $BITBUCKET_GIT_SSH_ORIGIN ./mirrored;
            cd ./mirrored;
            git fetch -p origin;

            # target the new location
            git remote set-url --push origin https://$GITHUB_CIBOT_USERNAME:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/$GITHUB_ORGNAME/$BITBUCKET_REPO_SLUG;

            # replicate
            git push --mirror;
```

During our transition period, this should work fine for us unless you can see any issues

**Comment by Enteee** [comment]
glad you found a solution that works for you :+1:
